export * from './getRequest'
export * from './postRequest'
export * from './putRequest'
export * from './deleteRequest'
export * from './getDateAndDay'
export * from './getTypeOfTheWeek'
export * from './selectUser'
export * from './isLessonsDTOsEqual'
